### ISSUE TITLE
Exactcure Lopinavir is not displayed

### ISSUE THREAD

**Issue by Jcchemin** [MaladieCoronavirus/boite-a-outils#54]
The "Exactcure lopinavir" card is not displayed on the website, it should appear in "praticiens" & "etablissements"

https://github.com/MaladieCoronavirus/boite-a-outils/blob/master/src/resources/exactcure-lopinavir

**Comment by rolebi** [comment]
@Jcchemin merci pour ton retour, il y a eu un problème sur le package livré sur nos environnement de production. Je viens de re-livrer et tes modifications sont bien présentes.

**Comment by Jcchemin** [comment]
Super ! merci beaucoup :-)
